"""next_version

Revision ID: 70820378e527
Revises: 4a4f00899339
Create Date: 2023-10-11 23:42:24.435921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70820378e527'
down_revision = '4a4f00899339'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(length=512), nullable=False),
    sa.Column('combination_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['combination_id'], ['application.combinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation'),
    schema='application'
    )
    op.create_index(op.f('ix_application_recommendation_id'), 'recommendation', ['id'], unique=False, schema='application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_recommendation_id'), table_name='recommendation', schema='application')
    op.drop_table('recommendation', schema='application')
    # ### end Alembic commands ###
